Больше деталей
htmlacademy-javascript/1743839-kekstagram-32 pull request #3
Opened 2024-07-04 06:39 UTC by Dimriu

При выполнении домашнего задания больше опирался на полученные знания из теории и тренажеров.
Но при дальнейшем прохождении курса, где разбирали как выполнить домашнее задание, мой вариант стал больше похож на гипотезу.

2024-07-04 08:01 UTC, Kartaviy-arteom requested changes

2024-07-04 08:01 UTC, Kartaviy-arteom commented on js/main.js
> +  const MESSAGES = ['Всё отлично!','В целом всё неплохо. Но не всё.','Когда вы делаете фотографию, хорошо бы убирать палец из кадра.',
константы нужно поднять в начало модуля. из всех функций
https://up.htmlacademy.ru/javascript/32/criteries#b10

2024-07-04 08:01 UTC, Kartaviy-arteom commented on js/main.js
> +  };
нужно исправить все ошибки линтеров

2024-07-04 08:01 UTC, Kartaviy-arteom commented on js/main.js
> + return j+101;
не понятно откуда тут появилось 101
https://up.htmlacademy.ru/javascript/32/criteries#d19
так же и в других функциях.

2024-07-04 08:01 UTC, Kartaviy-arteom commented on js/main.js
> +  return i+1;
i+1 не дает случайный индекс

2024-07-04 08:01 UTC, Kartaviy-arteom commented on js/main.js
> +function getRandomPhotos(i) {
эта функция просто создает путь для картинки. Наименование функции не соответствует тому что она делает

2024-07-13 12:21 UTC, Dimriu commented
Полностью переделал домашнее задание.

2024-07-13 12:24 UTC, Dimriu commented
Переделал домашнее задание

2024-07-13 12:26 UTC, closed without merging